# Generated by Django 4.2 on 2023-04-25 14:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ca119998-5ff7-4480-aa62-fb6edd7ebd9f'), primary_key=True, serialize=False),
        ),
    ]
